compile_pdf:
  image: aergus/latex
  script:
    - apt-get install -y inkscape
    - pdflatex -shell-escape main.tex
    - makeglossaries main
    - makeindex main.idx
    - pdflatex main.tex
  except:
    - dev
  artifacts:
    paths:
      - main.pdf
